import { type NextPage } from "next";
import Head from "next/head";
import { useUser, SignIn, UserButton } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {isSignedIn && (
            <>
              <h1 className="text-5xl font-extrabold tracking-tight text-[hsl(140,100%,70%)] sm:text-[5rem]">
                Sign out
              </h1>
              <UserButton />
            </>
          )}
          {!isSignedIn && (
            <>
              <h1 className="text-5xl font-extrabold tracking-tight text-[hsl(280,100%,70%)] sm:text-[5rem]">
                Sign In
              </h1>
              <SignIn />
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
